spring:
  jpa:
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jwt:
    secret: eiu8euj@112w^

  datasource:
    url: jdbc:mariadb://localhost:4306/conia_shop
    username: conia
    password: coniapw
    driver-class-name: org.mariadb.jdbc.Driver

